import { ElementImage, ElementRect, ElementText } from "~/stores/EditorStore";

export const defaultElements = {
  rect: {
    id: "",
    type: "rect",
    x: 0,
    y: 0,
    rotate: 0,
    width: 100,
    height: 100,
    backgroundColor: "#e41212",
    backgroundOpacity: 1,
    borderColor: "black",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderWidth: 1,
    variables: [],
    borderStyle: "solid",
  } as ElementRect,
  text: {
    id: "",
    type: "text",
    x: 0,
    y: 0,
    rotate: 0,
    width: 100,
    height: 100,
    color: "#000000",
    textColorOpacity: 1,
    textTransform: "none",
    fontSize: 16,
    fontWeight: 100,
    fontStyle: "normal",
    fontFamily: "Arial",
    textAlign: "left",
    content: "Text",
    lineHeight: 1.5,
    variables: [],
  } as ElementText,
  image: {
    id: "",
    type: "image",
    x: 0,
    y: 0,
    rotate: 0,
    width: 100,
    height: 100,
    src: null,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    objectFit: "cover",
    variables: [],
  } as ElementImage,
};
