import { Tree } from "~/stores/EditorStore";

export const defaultTree: Tree = {
  id: "1",
  type: "page",
  width: 1200,
  height: 630,
  backgroundColor: "#d1d5db",
  x: 0,
  y: 0,
  children: [
    {
      id: "qzdqzdqzd",
      type: "rect",
      x: 100,
      y: 100,
      width: 74,
      height: 74,
      backgroundColor: "#1bc529",
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderWidth: 0,
      borderColor: "red",
      borderStyle: "solid",
    },
    {
      id: "2vvvvv",
      type: "rect",
      x: 300,
      y: 100,
      width: 120,
      height: 60,
      backgroundColor: "#d42f2f",
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderWidth: 0,
      borderColor: "red",
      borderStyle: "solid",
    },
  ],
};
