import type {
	ImageElement,
	ImageElementWithVariables,
	RectElement,
	RectElementWithVariables,
	TextElement,
	TextElementWithVariables,
} from "~/stores/elementTypes";

export const defaultElements = {
	rect: {
		id: "",
		type: "rect",
		x: 0,
		y: 0,
		rotate: 0,
		width: 100,
		height: 100,
		backgroundColor: "#e41212",
		backgroundOpacity: 1,
		borderColor: "black",
		borderTopLeftRadius: 0,
		borderTopRightRadius: 0,
		borderBottomRightRadius: 0,
		borderBottomLeftRadius: 0,
		borderWidth: 1,
		variables: [],
	} as RectElementWithVariables,
	text: {
		id: "",
		type: "text",
		x: 0,
		y: 0,
		rotate: 0,
		width: 100,
		height: 100,
		color: "#000000",
		textColorOpacity: 1,
		textTransform: "none",
		fontSize: 28,
		fontWeight: 400,
		fontStyle: "normal",
		fontFamily: "Open Sans",
		textAlign: "left",
		content: "Text",
		lineHeight: 1.5,
		variables: [],
	} as TextElementWithVariables,
	image: {
		id: "",
		type: "image",
		x: 0,
		y: 0,
		rotate: 0,
		width: 100,
		height: 100,
		src: null,
		borderTopLeftRadius: 0,
		borderTopRightRadius: 0,
		borderBottomRightRadius: 0,
		borderBottomLeftRadius: 0,
		objectFit: "cover",
		variables: [],
	} as ImageElementWithVariables,
};
