import type { Tree } from "~/stores/EditorStore";
import { getPublicEnv } from "~/utils/getPublicEnv";

export type PublicTemplate = {
	name: string;
	tree: Tree;
	preview: string;
};

export const publicTemplates: PublicTemplate[] = [
	{
		name: "template1",
		tree: {
			x: 0,
			y: 0,
			id: "1",
			type: "page",
			width: 1200,
			height: 630,
			rotate: 1,
			children: [
				{
					x: 10,
					y: 10,
					id: "6c156adf-03a6-4eeb-94b2-2c687de0b9c8",
					blur: null,
					type: "rect",
					width: 1180,
					height: 611,
					rotate: 0,
					variables: [],
					borderType: null,
					shadowBlur: null,
					borderColor: null,
					borderWidth: null,
					shadowColor: null,
					shadowSpread: null,
					borderOpacity: null,
					shadowOpacity: null,
					shadowXOffset: null,
					shadowYOffset: null,
					backgroundColor: "#080708",
					backgroundOpacity: 1,
					borderTopLeftRadius: 0,
					borderTopRightRadius: 0,
					backgroundGradientType: null,
					borderBottomLeftRadius: 0,
					backgroundGradientAngle: null,
					borderBottomRightRadius: 0,
					backgroundGradientColorTo: null,
					backgroundGradientColorFrom: null,
					backgroundGradientColorToOpacity: null,
					backgroundGradientColorFromOpacity: null,
				},
				{
					x: 74,
					y: 77,
					id: "137b1f3d-e011-4309-947e-e16e56ba11c7",
					blur: null,
					type: "text",
					color: "#e88aff",
					width: 567,
					height: 199,
					rotate: 0,
					content: "This is your super blog title",
					fontSize: "68",
					fontStyle: "normal",
					textAlign: "left",
					variables: [],
					fontFamily: "Open Sans",
					fontWeight: 700,
					lineHeight: 1.5,
					textTransform: "none",
					textShadowBlur: null,
					textShadowColor: null,
					textColorOpacity: 1,
					textShadowOpacity: null,
					textShadowXOffset: null,
					textShadowYOffset: null,
				},
				{
					x: 90,
					y: 394,
					id: "325d5380-83eb-46b3-b7c5-a668a018b536",
					src: `${getPublicEnv(
						"WEBSITE_URL",
					)}/images/public-templates/contents/0cca067b-33e0-4485-a908-9b5d16dabf5c.png`,
					blur: null,
					type: "image",
					width: 129,
					height: 128,
					rotate: 0,
					objectFit: "cover",
					variables: [],
					borderType: "outside",
					shadowBlur: null,
					borderColor: "#e88aff",
					borderWidth: 4,
					shadowColor: null,
					shadowSpread: null,
					borderOpacity: 1,
					shadowOpacity: null,
					shadowXOffset: null,
					shadowYOffset: null,
					borderTopLeftRadius: 200,
					borderTopRightRadius: 200,
					borderBottomLeftRadius: 200,
					borderBottomRightRadius: 200,
				},
				{
					x: 240,
					y: 402,
					id: "034fe8a8-12fe-4cd6-94be-96aaa739d971",
					blur: null,
					type: "text",
					color: "#e5c6ee",
					width: 209,
					height: 53,
					rotate: 0,
					content: "John Doe",
					fontSize: "36",
					fontStyle: "normal",
					textAlign: "left",
					variables: [],
					fontFamily: "Open Sans",
					fontWeight: 600,
					lineHeight: 1.5,
					textTransform: "none",
					textShadowBlur: null,
					textShadowColor: null,
					textColorOpacity: 1,
					textShadowOpacity: null,
					textShadowXOffset: null,
					textShadowYOffset: null,
				},
				{
					x: 242,
					y: 460,
					id: "8f64061b-04f7-4ab5-b229-40a76ace5804",
					blur: null,
					type: "text",
					color: "#b8b8b8",
					width: 260,
					height: 53,
					rotate: 0,
					content: "my-blog.com",
					fontSize: "32",
					fontStyle: "normal",
					textAlign: "left",
					variables: [],
					fontFamily: "Open Sans",
					fontWeight: 400,
					lineHeight: 1.5,
					textTransform: "none",
					textShadowBlur: null,
					textShadowColor: null,
					textColorOpacity: 1,
					textShadowOpacity: null,
					textShadowXOffset: null,
					textShadowYOffset: null,
				},
			],
			variables: [],
			backgroundColor: "#e88aff",
			backgroundOpacity: 1,
		},
		preview: `${getPublicEnv(
			"WEBSITE_URL",
		)}/images/public-templates/previews/render-4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945.png`,
	},
	{
		name: "template2",
		tree: {
			x: 0,
			y: 0,
			id: "1",
			type: "page",
			width: 1200,
			height: 630,
			rotate: 1,
			children: [
				{
					x: 0,
					y: 0,
					id: "0d1a6173-7998-4b25-b406-5760da8c6680",
					src: `${getPublicEnv(
						"WEBSITE_URL",
					)}/images/public-templates/contents/72991d9f-f4e6-47cd-b5c9-f44b4e657c90.png`,
					blur: null,
					type: "image",
					width: 1200,
					height: 630,
					rotate: 0,
					objectFit: "cover",
					variables: [],
					borderType: null,
					shadowBlur: null,
					borderColor: null,
					borderWidth: null,
					shadowColor: null,
					shadowSpread: null,
					borderOpacity: null,
					shadowOpacity: null,
					shadowXOffset: null,
					shadowYOffset: null,
					borderTopLeftRadius: 0,
					borderTopRightRadius: 0,
					borderBottomLeftRadius: 0,
					borderBottomRightRadius: 0,
				},
				{
					x: 0,
					y: 0,
					id: "eebf53a9-e469-4409-8eb6-e039898393c4",
					blur: null,
					type: "rect",
					width: 1200,
					height: 630,
					rotate: 0,
					variables: [],
					borderType: null,
					shadowBlur: null,
					borderColor: null,
					borderWidth: null,
					shadowColor: null,
					shadowSpread: null,
					borderOpacity: null,
					shadowOpacity: null,
					shadowXOffset: null,
					shadowYOffset: null,
					backgroundColor: "#0e0e0e",
					backgroundOpacity: 0.6,
					borderTopLeftRadius: 0,
					borderTopRightRadius: 0,
					backgroundGradientType: null,
					borderBottomLeftRadius: 0,
					backgroundGradientAngle: null,
					borderBottomRightRadius: 0,
					backgroundGradientColorTo: null,
					backgroundGradientColorFrom: null,
					backgroundGradientColorToOpacity: null,
					backgroundGradientColorFromOpacity: null,
				},
				{
					x: 167,
					y: 256,
					id: "45132e1f-715f-475c-99cb-ac084d7d96b5",
					blur: null,
					type: "text",
					color: "#fafafa",
					width: 829,
					height: 220,
					rotate: 0,
					content: "This is your super blog article",
					fontSize: "64",
					fontStyle: "normal",
					textAlign: "center",
					variables: [],
					fontFamily: "Open Sans",
					fontWeight: 700,
					lineHeight: 1.5,
					textTransform: "none",
					textShadowBlur: null,
					textShadowColor: null,
					textColorOpacity: 1,
					textShadowOpacity: null,
					textShadowXOffset: null,
					textShadowYOffset: null,
				},
				{
					x: 463,
					y: 100,
					id: "923fc4d2-3438-49e3-8f0d-7c6c87042438",
					src: `${getPublicEnv(
						"WEBSITE_URL",
					)}/images/public-templates/contents/085d3762-fefe-4292-85cc-2480d6839b78.png`,
					blur: null,
					type: "image",
					width: 270,
					height: 53,
					rotate: 0,
					objectFit: "cover",
					variables: [],
					borderType: null,
					shadowBlur: null,
					borderColor: null,
					borderWidth: null,
					shadowColor: null,
					shadowSpread: null,
					borderOpacity: null,
					shadowOpacity: null,
					shadowXOffset: null,
					shadowYOffset: null,
					borderTopLeftRadius: 0,
					borderTopRightRadius: 0,
					borderBottomLeftRadius: 0,
					borderBottomRightRadius: 0,
				},
			],
			variables: [],
			backgroundColor: "#ffffff",
			backgroundOpacity: 1,
		},
		preview: `${getPublicEnv(
			"WEBSITE_URL",
		)}/images/public-templates/previews/render-4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b946.png`,
	},
];
